// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v4.22.3
// source: test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// expect:
// Color_Color_Red -> Color_Red
type Color int32

const (
	Color_Color_Invalid Color = 0
	Color_Color_Red     Color = 2
	Color_Color_Green   Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "Color_Invalid",
		2: "Color_Red",
		3: "Color_Green",
	}
	Color_value = map[string]int32{
		"Color_Invalid": 0,
		"Color_Red":     2,
		"Color_Green":   3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type ToyBricks_Shape int32

const (
	ToyBricks_Shape_Invalid ToyBricks_Shape = 0
	ToyBricks_Shape_Circle  ToyBricks_Shape = 1
	ToyBricks_Shape_square  ToyBricks_Shape = 2
)

// Enum value maps for ToyBricks_Shape.
var (
	ToyBricks_Shape_name = map[int32]string{
		0: "Shape_Invalid",
		1: "Shape_Circle",
		2: "Shape_square",
	}
	ToyBricks_Shape_value = map[string]int32{
		"Shape_Invalid": 0,
		"Shape_Circle":  1,
		"Shape_square":  2,
	}
)

func (x ToyBricks_Shape) Enum() *ToyBricks_Shape {
	p := new(ToyBricks_Shape)
	*p = x
	return p
}

func (x ToyBricks_Shape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToyBricks_Shape) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[1].Descriptor()
}

func (ToyBricks_Shape) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[1]
}

func (x ToyBricks_Shape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToyBricks_Shape.Descriptor instead.
func (ToyBricks_Shape) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0, 0}
}

// expect:
//
type ToyBricks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ToyBricks) Reset() {
	*x = ToyBricks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToyBricks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToyBricks) ProtoMessage() {}

func (x *ToyBricks) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToyBricks.ProtoReflect.Descriptor instead.
func (*ToyBricks) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *ToyBricks) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x5b, 0x0a, 0x09, 0x54, 0x6f, 0x79, 0x42, 0x72, 0x69, 0x63, 0x6b, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x3e, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x70,
	0x65, 0x5f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x68, 0x61, 0x70, 0x65, 0x5f, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x68, 0x61, 0x70, 0x65, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x10, 0x02, 0x2a,
	0x3a, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x5f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x52, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x5f, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x10, 0x03, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_proto_goTypes = []interface{}{
	(Color)(0),           // 0: test.Color
	(ToyBricks_Shape)(0), // 1: test.ToyBricks.Shape
	(*ToyBricks)(nil),    // 2: test.ToyBricks
}
var file_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToyBricks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
